# Generated by Django 2.2 on 2021-01-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('original_title', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.CharField(blank=True, max_length=32, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.CharField(blank=True, max_length=128, null=True)),
                ('director', models.CharField(blank=True, max_length=128, null=True)),
                ('writer', models.CharField(blank=True, max_length=256, null=True)),
                ('production_company', models.CharField(blank=True, max_length=256, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avg_vote', models.FloatField(blank=True, null=True)),
                ('votes', models.FloatField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=56, null=True)),
                ('usa_gross_income', models.CharField(blank=True, max_length=56, null=True)),
                ('worlwide_gross_income', models.CharField(blank=True, max_length=56, null=True)),
                ('metascore', models.FloatField(blank=True, null=True)),
                ('reviews_from_users', models.FloatField(blank=True, null=True)),
                ('reviews_from_critics', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('list_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('movies', models.ManyToManyField(blank=True, related_name='movies', to='movies.Movie')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MovieList',
            },
        ),
    ]
