# Generated by Django 2.2 on 2021-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('original_title', models.CharField(blank=True, max_length=256)),
                ('year', models.CharField(blank=True, max_length=32)),
                ('date_published', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=128)),
                ('duration', models.FloatField(blank=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(blank=True, max_length=128)),
                ('director', models.CharField(blank=True, max_length=128)),
                ('writer', models.CharField(blank=True, max_length=256)),
                ('production_company', models.CharField(blank=True, max_length=256)),
                ('actors', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('avg_vote', models.FloatField(blank=True)),
                ('votes', models.FloatField(blank=True)),
                ('budget', models.CharField(blank=True, max_length=56)),
                ('usa_gross_income', models.CharField(blank=True, max_length=56)),
                ('worlwide_gross_income', models.CharField(blank=True, max_length=56)),
                ('metascore', models.FloatField(blank=True)),
                ('reviews_from_users', models.FloatField(blank=True)),
                ('reviews_from_critics', models.FloatField(blank=True)),
            ],
        ),
    ]
